### ISSUE TITLE
DPU doesn't setup virtual path for output files

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/UVPlugin-ISO2709ToMarcXML#1]
Issue created from UnifiedViews/Plugins#128 in [this comment](UnifiedViews/Plugins#128#issuecomment-93695772):

DPU does not properly sets up VirtualPath for output files. Every DPU must define VirtualPath for output file entries using VirtualPathHelper.

Solution: VirtualPath must be properly set up for ISO2709ToMarcXML

**Comment by jindrichmynarz** [comment]
@skrchnavy: Any progress on this issue? This is a blocker for the Slovak National Library COMSODE pilot (and probably quite easy to fix), so it would be great if it was fixed soon.

**Comment by ghost** [comment]
Resolved
