### ISSUE TITLE
Not possible to import t-ISO2509ToMarcXML

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/UVPlugin-ISO2709ToMarcXML#3]
@pgo-eea-sk comment in UnifiedViews/Core#395 whe import of DPU returned unexpected exception:

In this case the problem is, that t-ISO2709ToMarcXML in provided pipeline to import has different name than t-ISO2709ToMarcXML from commit e4242f1f3d76b4ee5f19932c39895c3f9fbbf5fc
The name from provided pipeline import is T-ISO2709ToMarcXML, but when I create DPU template from last commit, the name is uv-t-ISO2709ToMarcXML. So template.getByName("T-ISO2709ToMarcXML") returns null because the name in the database is uv-t-ISO2709ToMarcXML.

**Comment by skrchnavy** [comment]
@mkl-eea-sk do you have proposal for fix of this? Or can we close it? ( @jindrichmynarz your opinion?)

**Comment by skrchnavy** [comment]
@jindrichmynarz is this issue valid?

**Comment by jindrichmynarz** [comment]
It's not clear from the description how to reproduce this issue.

**Comment by skrchnavy** [comment]
@jindrichmynarz then you don't have any blocker related to this, so closing
